name: Build Flutter APK
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # NEW: This tells GitHub to run all commands inside your app's folder
    defaults:
      run:
        working-directory: ./flutter_pro_s5

    steps:
    - uses: actions/checkout@v4
    
    # 1. Setup Java
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17' 
        
    # 2. Setup Flutter
    - uses: subosito/flutter-action@v3
      with:
        flutter-version: '3.x'
        
    # 3. Get dependencies (Will now run inside ./hostel_app)
    - run: flutter pub get
      
    # 4. Build the APK (Will now run inside ./hostel_app)
    - run: flutter build apk --release
      
    # 5. Upload the final APK
    - uses: actions/upload-artifact@v4
      with:
        name: release-apk
        # NEW: The path must include your hostel_app folder
        path: hostel_app/build/app/outputs/flutter-apk/app-release.apk
